
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Optional if Dockerfile is at root
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      uvicorn brigantes.asgi:application --host 0.0.0.0 --port 8000
      "
    volumes:
      - /opt/brigantes/static:/opt/static
      - /opt/brigantes/media:/opt/media
    environment:
      - DJANGO_SECRET_KEY=efsdgewdgf
      - DJANGO_DATABASE_URL=mysql://root:root@host.docker.internal:3306/brigantes
      - DJANGO_SETTINGS_MODULE=brigantes.settings.prod
    expose:
      - "8000"


  nginx:
    image: nginx:stable
    ports:
      - "8009:80"
    volumes:
      - /opt/brigantes/static:/app/static
      - /opt/brigantes/media:/app/media
      - /opt/brigantes/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

# volumes:
  # /opt/brigantes/media:
  # /opt/brigantes/static:


# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "80:80"
#     environment:
#       - DEBUG=0
#     volumes:
#       - static_volume:/opt/staticfiles
#     depends_on:
#       - db  # if you have a database service

# volumes:
#   static_volume: