services:
  web:
    build: .
    command: gunicorn brigantes.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=brigantes.settings.prod
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL}
    expose:
      - "8000"  # Expose internal port for nginx to use

  nginx:
    image: nginx:stable
    ports:
      - "8009:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
