# Generated by Django 5.2.2 on 2025-06-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('site_title', models.CharField(max_length=50)),
            ],
        ),
    ]
